### ISSUE TITLE
Salesforce Rest connector test suite fails at enrich mediator 

### ISSUE THREAD

**Issue by abeykoon** [wso2/micro-integrator#2153]
**Description:**

Setup ESB Salesforce REST connector test suite with MI 4.0.0 Alpha 
Following test fails

```
    /**
     * Test case for create method.
     */
    @Test(enabled = true, description = "salesforcerest {create} integration test.")
    public void create() throws IOException, JSONException {

        String methodName = "create";
        RestResponse<JSONObject> esbRestResponse = sendJsonRestRequest(getProxyServiceURLHttp(methodName), "POST", esbRequestHeadersMap, "create.json");
        String apiEndPoint = connectorProperties.getProperty("apiUrl") + "/services/data/" + connectorProperties.getProperty("apiVersion") + "/sobjects/" + connectorProperties.getProperty("sObjectName");
        RestResponse<JSONObject> apiRestResponse = sendJsonRestRequest(apiEndPoint, "GET", apiRequestHeadersMap);
        log.info("======= RESPONSE STATUS: " + esbRestResponse.getHttpStatusCode()+ "===================");
        String id = esbRestResponse.getBody().getString("id").toString();
        connectorProperties.put("id",id);
        Assert.assertEquals(esbRestResponse.getHttpStatusCode(), 201);
        Assert.assertEquals(apiRestResponse.getHttpStatusCode(), 200);
        Assert.assertEquals(esbRestResponse.getBody().getString("id"), apiRestResponse.getBody().getJSONArray("recentItems").getJSONObject(0).getString("Id"));
    }
```

Same passes when tested with EI 6.6.0

**Comment by abeykoon** [comment]
Error Trace. According to that, it fails at enrich mediator. Connector implementation should be using the enrich mediator. It says incoming json is malformed.

```
INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - [2021-03-13 08:51:27,735]  INFO {LogMediator} - {proxy:create} To: /services/create,MessageID: urn:uuid:f6e71498-c993-4828-ab06-d479cffb90e0,Direction: request,Payload: {
INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] -   "accessToken": "00D2x000002PpUE!ASAAQPE9DuLPkM24mkYoWqvF4r6RAhxn0qeV75dq73F8ElyOLFkClGWiy9owXhLl5UG9oPwM.o7ZwIHQi5Dz3.371BtQZQ8Y",
INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] -   "apiUrl": "https://ap17.salesforce.com",
INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] -   "clientId": "3MVG97quAmFZJfVyFRP5qtSVKIU.u5Nkeu9fRDAay48nHAIwWSLzSL_1FduiBQcu3bC6oHKzUlekWfL2xv_Ok",
INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] -   "refreshToken": "5Aep861Xq7VoDavIt7XOEsImKR.djBH5FPPyRaHtdf3LZjoc4pnVtP.lgbBFPVyMtL98MPSu8SYd8XpcyP.i.hW",
INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] -   "clientSecret": "CA422811CDE80637D2C35983CB095B1C32A4BC315FD8E3795156AE69EBA62D8A",
INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] -   "hostName": "https://login.salesforce.com",
INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] -   "apiVersion": "v32.0",
INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] -   "registryPath": "connectors/Salesforcerest",
INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] -   "intervalTime": "2400000",
INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] -   "sObjectName": "Account",
INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] -   "fieldAndValue": {
INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] -     "name": "testWSO2qq",
INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] -     "description": "This is for testing purpose"
INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] -   }
INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - }
INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - [2021-03-13 08:51:27,760] ERROR {FilterMediator} - {proxy:create} com.google.gson.stream.MalformedJsonException: Expected name at line 1 column 2 path $. com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Expected name at line 1 column 2 path $.
INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - 	at com.google.gson.internal.Streams.parse(Streams.java:60)
INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - 	at com.google.gson.JsonParser.parse(JsonParser.java:84)
INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - 	at com.google.gson.JsonParser.parse(JsonParser.java:59)
INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - 	at com.google.gson.JsonParser.parse(JsonParser.java:45)
INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - 	at org.apache.synapse.mediators.elementary.Source.evaluateJson(Source.java:318)
INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - 	at org.apache.synapse.mediators.elementary.EnrichMediator.mediate(EnrichMediator.java:221)
INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - 	at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:109)
INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - 	at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:71)
INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - 	at org.apache.synapse.mediators.filters.FilterMediator.mediate(FilterMediator.java:171)
INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - 	at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:109)
INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - 	at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:71)
INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - 	at org.apache.synapse.mediators.filters.FilterMediator.mediate(FilterMediator.java:171)
INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - 	at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:109)
INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - 	at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:71)
INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - 	at org.apache.synapse.mediators.template.TemplateMediator.mediate(TemplateMediator.java:136)
INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - 	at org.apache.synapse.mediators.template.InvokeMediator.mediate(InvokeMediator.java:170)
INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - 	at org.apache.synapse.mediators.template.InvokeMediator.mediate(InvokeMediator.java:93)
INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - 	at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:109)
INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - 	at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:71)
INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - 	at org.apache.synapse.mediators.template.TemplateMediator.mediate(TemplateMediator.java:136)
INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - 	at org.apache.synapse.mediators.template.InvokeMediator.mediate(InvokeMediator.java:170)
INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - 	at org.apache.synapse.mediators.template.InvokeMediator.mediate(InvokeMediator.java:93)
INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - 	at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:109)
INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - 	at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:71)
INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - 	at org.apache.synapse.mediators.base.SequenceMediator.mediate(SequenceMediator.java:158)
INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - 	at org.apache.synapse.core.axis2.ProxyServiceMessageReceiver.receive(ProxyServiceMessageReceiver.java:226)
INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - 	at org.apache.axis2.engine.AxisEngine.receive(AxisEngine.java:180)
INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - 	at org.apache.synapse.transport.passthru.ServerWorker.processNonEntityEnclosingRESTHandler(ServerWorker.java:369)
INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - 	at org.apache.synapse.transport.passthru.ServerWorker.processEntityEnclosingRequest(ServerWorker.java:428)
INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - 	at org.apache.synapse.transport.passthru.ServerWorker.run(ServerWorker.java:182)
INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - 	at org.apache.axis2.transport.base.threads.NativeWorkerPool$1.run(NativeWorkerPool.java:172)
INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - 	at java.lang.Thread.run(Thread.java:748)
INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - Caused by: com.google.gson.stream.MalformedJsonException: Expected name at line 1 column 2 path $.
INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - 	at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1568)
INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - 	at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:513)
INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - 	at com.google.gson.stream.JsonReader.hasNext(JsonReader.java:414)
INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - 	at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:722)
INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - 	at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:698)
INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - 	at com.google.gson.internal.Streams.parse(Streams.java:48)
INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - 	... 33 more
INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] -
```

**Comment by abeykoon** [comment]
The update to the enrich mediator [1] is done through the following fix [2]: 

[1] https://github.com/wso2/wso2-synapse/blob/master/modules/core/src/main/java/org/apache/synapse/mediators/elementary/EnrichMediator.java#L221

[2]. https://github.com/wso2/wso2-synapse/commit/a68a018f397c7235febde939250e9c66ebb0493c#diff-706374c51132669cc0125007967fea2e7fd4911ed93b67a3db94c154028459cbR181

**Comment by abeykoon** [comment]
The issue was json is encoded inside synapse in a wrong manner. It will get fixed by 
https://github.com/wso2/wso2-synapse/pull/1745

**Comment by sanjeewa-malalgoda** [comment]
I can see PR mentioned above merged. Are we still seeing this issue?

**Comment by sanjeewa-malalgoda** [comment]
@dulanjalidilmi have you started verifying this issue?

**Comment by dulanjalidilmi** [comment]
I am checking this issue.

**Comment by dulanjalidilmi** [comment]
This issue is fixed.
